 // ===== DONNÉES DES MÉTIERS (35 MÉTIERS) =====
console.log("📊 Initialisation des données métiers...");

window.jobsData = [
    {
    "id": 1,
    "nom": "Médecin",
    "domaine": "SANTÉ & MÉDECINE",
    "description": "Diagnostique et soigne les maladies. Peut exercer à l'hôpital ou en cabinet.",
    "salaire": "8 000 - 50 000 DH",
    "etudes": "Bac + 7 à +12",
    "competences": "Résistance au stress, empathie, précision",
    "tagsQuiz": ["sciences", "humain", "responsabilité"],
    "formationsLiees": ["Facultés de Médecine (FMP)"],
    "parcours": "Bac S → Concours de médecine (FMP) → 7 ans études → Résidanat (4-5 ans) pour spécialisation",
    "bac": "S"
  },
  {
    "id": 2,
    "nom": "Pharmacien",
    "domaine": "SANTÉ & MÉDECINE",
    "description": "Expert du médicament. Dispense, conseille, peut diriger une pharmacie ou travailler dans l'industrie.",
    "salaire": "7 000 - 25 000 DH",
    "etudes": "Bac + 6",
    "competences": "Rigueur scientifique, sens du contact, gestion",
    "tagsQuiz": ["sciences", "conseil", "précision"],
    "formationsLiees": ["Facultés de Médecine et de Pharmacie (FMP)"],
    "parcours": "Bac S → Concours de pharmacie (FMP) → 1 an tronc commun + 5 ans cycle pharmacie",
    "bac": "S"
  },
  {
    "id": 3,
    "nom": "Chirurgien-dentiste",
    "domaine": "SANTÉ & MÉDECINE",
    "description": "Spécialiste des soins dentaires (caries, détartrage, implants, orthodontie).",
    "salaire": "8 000 - 40 000 DH",
    "etudes": "Bac + 6",
    "competences": "Habileté manuelle, patience, sens esthétique",
    "tagsQuiz": ["soin", "manuel", "précision"],
    "formationsLiees": ["Facultés de Médecine Dentaire"],
    "parcours": "Bac S → Concours de médecine dentaire → 1 an tronc commun + 5 ans cycle odontologie",
    "bac": "S"
  },
  {
    "id": 4,
    "nom": "Sage-femme",
    "domaine": "SANTÉ & MÉDECINE",
    "description": "Accompagne les femmes pendant la grossesse, pratique les accouchements normaux et suit la mère et le nouveau-né.",
    "salaire": "6 000 - 15 000 DH",
    "etudes": "Bac + 4",
    "competences": "Grande résistance, empathie, sang-froid",
    "tagsQuiz": ["soin", "humain", "responsabilité"],
    "formationsLiees": ["Instituts de Formation aux Carrières de Santé (IFCS)"],
    "parcours": "Bac S ou SVT → Concours IFCS (sage-femme) → 4 ans de formation",
    "bac": "S ou SVT"
  },
  {
    "id": 5,
    "nom": "Infirmier",
    "domaine": "SANTÉ & MÉDECINE",
    "description": "Dispense les soins de base, suit l'état des patients, assiste le médecin.",
    "salaire": "5 000 - 12 000 DH",
    "etudes": "Bac + 3",
    "competences": "Dévouement, résistance physique, travail en équipe",
    "tagsQuiz": ["soin", "équipe", "humain"],
    "formationsLiees": ["Instituts de Formation aux Carrières de Santé (IFCS)"],
    "parcours": "Bac (scientifique ou littéraire) → Concours IFCS (infirmier) → 3 ans de formation",
    "bac": "Toutes"
  },
  {
    "id": 6,
    "nom": "Kinésithérapeute",
    "domaine": "SANTÉ & MÉDECINE",
    "description": "Rééduque les patients après un accident ou une opération, traite les douleurs musculaires et articulaires.",
    "salaire": "7 000 - 30 000 DH",
    "etudes": "Bac + 4",
    "competences": "Bonne condition physique, sens du contact, patience",
    "tagsQuiz": ["soin", "sport", "rééducation"],
    "formationsLiees": ["Instituts de Formation aux Carrières de Santé (IFCS)"],
    "parcours": "Bac S → Concours IFCS (kinésithérapie) → 4 ans de formation",
    "bac": "S"
  },
  {
    "id": 7,
    "nom": "Vétérinaire",
    "domaine": "SANTÉ & MÉDECINE",
    "description": "Médecin des animaux. Soigne les animaux de compagnie, de ferme, ou travaille dans la santé publique.",
    "salaire": "7 000 - 25 000 DH",
    "etudes": "Bac + 6",
    "competences": "Amour des animaux, sang-froid, sens de l'observation",
    "tagsQuiz": ["animaux", "sciences", "soin"],
    "formationsLiees": ["Institut Agronomique et Vétérinaire Hassan II (IAV)"],
    "parcours": "Bac S → Concours d'entrée à l'IAV Hassan II → 6 ans d'études",
    "bac": "S"
  },
  {
    "id": 8,
    "nom": "Ingénieur d'État",
    "domaine": "INGÉNIERIE & TECHNOLOGIE",
    "description": "Conçoit, innove et résout des problèmes techniques complexes dans divers secteurs (BTP, informatique, industrie).",
    "salaire": "8 000 - 30 000 DH",
    "etudes": "Bac + 5",
    "competences": "Esprit logique, créativité, gestion de projet",
    "tagsQuiz": ["technique", "innovation", "problèmes"],
    "formationsLiees": ["ENSA", "EMI", "ENIM", "EHTP"],
    "parcours": "Bac Sciences Maths → Classes Préparatoires (CPGE) → Concours Grande École OU Faculté des Sciences → Master",
    "bac": "Sciences Maths"
  },
  {
    "id": 9,
    "nom": "Architecte",
    "domaine": "INGÉNIERIE & TECHNOLOGIE",
    "description": "Conçoit des bâtiments et des espaces, alliant esthétique, fonctionnalité et respect des normes.",
    "salaire": "7 000 - 25 000 DH",
    "etudes": "Bac + 6",
    "competences": "Créativité, sens de l'espace, rigueur technique",
    "tagsQuiz": ["créatif", "dessin", "construction"],
    "formationsLiees": ["École Nationale d'Architecture (ENA)"],
    "parcours": "Bac Sciences Maths ou toute filière → Concours de l'ENA → 6 ans d'études",
    "bac": "Toutes"
  },
  {
    "id": 10,
    "nom": "Développeur Informatique",
    "domaine": "INGÉNIERIE & TECHNOLOGIE",
    "description": "Crée des logiciels, des applications ou des sites web. Métier très demandé dans tous les secteurs.",
    "salaire": "7 000 - 25 000 DH",
    "etudes": "Bac + 2 à +5",
    "competences": "Logique, patience, créativité",
    "tagsQuiz": ["informatique", "logique", "création"],
    "formationsLiees": ["ENSIAS", "1337", "YouCode", "Facultés des Sciences"],
    "parcours": "Bac Sciences Maths → École d'ingénieur/spécialisée OU Bac+2 (DUT/BTS) → École/Formation continue",
    "bac": "Sciences Maths"
  },
  {
    "id": 11,
    "nom": "Expert en Cybersécurité",
    "domaine": "INGÉNIERIE & TECHNOLOGIE",
    "description": "Protège les systèmes informatiques des entreprises contre les pirates et les virus.",
    "salaire": "8 000 - 35 000 DH",
    "etudes": "Bac + 5",
    "competences": "Esprit analytique, éthique, curiosité",
    "tagsQuiz": ["informatique", "sécurité", "défis"],
    "formationsLiees": ["ENSIAS", "EMI", "Écoles privées spécialisées"],
    "parcours": "Bac Sciences Maths → École d'ingénieur en informatique → Spécialisation en sécurité",
    "bac": "Sciences Maths"
  },
  {
    "id": 12,
    "nom": "Data Analyst",
    "domaine": "INGÉNIERIE & TECHNOLOGIE",
    "description": "Analyse de grandes quantités de données pour en extraire des informations utiles à la prise de décision.",
    "salaire": "8 000 - 30 000 DH",
    "etudes": "Bac + 5",
    "competences": "Esprit mathématique, curiosité, rigueur",
    "tagsQuiz": ["données", "maths", "analyse"],
    "formationsLiees": ["ENSIAS", "EMI", "ENSA", "Écoles de Commerce"],
    "parcours": "Bac Sciences Maths → École d'ingénieur/commerce ou Master en statistiques",
    "bac": "Sciences Maths"
  },
  {
    "id": 13,
    "nom": "Géomètre-topographe",
    "domaine": "INGÉNIERIE & TECHNOLOGIE",
    "description": "Mesure et délimite avec précision les terrains pour les projets de construction, les cartes, ou les bornages.",
    "salaire": "6 000 - 20 000 DH",
    "etudes": "Bac + 2 à +5",
    "competences": "Précision, sens de l'observation, travail sur le terrain",
    "tagsQuiz": ["terrain", "précision", "technique"],
    "formationsLiees": ["École Nationale de Géomètre Topographe (ENGTP)", "BTS/DUT spécialisés"],
    "parcours": "Bac Sciences → BTS Géomètre Topographe ou DUT puis Licence Pro ou intégrer l'ENGTP",
    "bac": "Sciences"
  },
  {
    "id": 14,
    "nom": "Avocat",
    "domaine": "DROIT, GESTION & COMMERCE",
    "description": "Défend les intérêts des clients en justice et les conseille dans leurs démarches juridiques.",
    "salaire": "6 000 - 50 000 DH",
    "etudes": "Bac + 5 + Stage + Examen",
    "competences": "Éloquence, esprit d'analyse, résistance au stress",
    "tagsQuiz": ["justice", "parler", "analyse"],
    "formationsLiees": ["Facultés de Droit"],
    "parcours": "Bac → Licence en Droit → Master en Droit → Stage chez un avocat → Examen du Barreau",
    "bac": "Toutes"
  },
  {
    "id": 15,
    "nom": "Notaire",
    "domaine": "DROIT, GESTION & COMMERCE",
    "description": "Officier public qui authentifie les actes juridiques (contrats de mariage, ventes immobilières, successions).",
    "salaire": "20 000 - 80 000 DH",
    "etudes": "Bac + 6 + Stage + Examen",
    "competences": "Rigueur extrême, discrétion, sens du contact",
    "tagsQuiz": ["droit", "rigueur", "contrats"],
    "formationsLiees": ["École Supérieure de Notariat (ESN)", "Facultés de Droit"],
    "parcours": "Bac → Licence en Droit → Master en Droit Notarial → Stage en étude notariale → Examen final",
    "bac": "Toutes"
  },
  {
    "id": 16,
    "nom": "Expert-comptable",
    "domaine": "DROIT, GESTION & COMMERCE",
    "description": "Tient, contrôle et certifie les comptes des entreprises. Conseille sur la gestion financière et fiscale.",
    "salaire": "7 000 - 50 000 DH",
    "etudes": "Bac + 8",
    "competences": "Rigueur absolue, esprit mathématique, discrétion",
    "tagsQuiz": ["chiffres", "organisation", "rigueur"],
    "formationsLiees": ["Écoles de Commerce et de Gestion", "Universités"],
    "parcours": "Bac (Éco ou Maths) → DCG → DSCG → Stage → Examen final d'Expert-Comptable",
    "bac": "Éco ou Sciences Maths"
  },
  {
    "id": 17,
    "nom": "Comptable",
    "domaine": "DROIT, GESTION & COMMERCE",
    "description": "Gère les opérations financières quotidiennes d'une entreprise (factures, paie, déclarations fiscales).",
    "salaire": "4 000 - 12 000 DH",
    "etudes": "Bac + 2 à +3",
    "competences": "Méthode, rigueur, fiabilité",
    "tagsQuiz": ["chiffres", "organisation", "méthode"],
    "formationsLiees": ["BTS Comptabilité et Gestion", "DUT GEA"],
    "parcours": "Bac (souvent Éco) → BTS Comptabilité Gestion ou DUT Gestion des Entreprises et Administrations (GEA)",
    "bac": "Éco"
  },
  {
    "id": 18,
    "nom": "Analyste financier",
    "domaine": "DROIT, GESTION & COMMERCE",
    "description": "Étudie les entreprises et les marchés pour conseiller sur les investissements.",
    "salaire": "8 000 - 35 000 DH",
    "etudes": "Bac + 5",
    "competences": "Esprit d'analyse, curiosité économique, résistance à la pression",
    "tagsQuiz": ["finance", "analyse", "marchés"],
    "formationsLiees": ["Écoles de Commerce (ISCAE, ESC)", "Écoles d'Ingénieur"],
    "parcours": "Bac Sciences Maths/Éco → CPGE ou Université → Grande École de Commerce/Ingénieur → Master spécialisé en Finance",
    "bac": "Sciences Maths ou Éco"
  },
  {
    "id": 19,
    "nom": "Professeur",
    "domaine": "ÉDUCATION, SOCIAL & SÉCURITÉ",
    "description": "Enseigne une matière (Maths, Français, SVT...) dans un collège ou lycée public.",
    "salaire": "6 000 - 13 000 DH",
    "etudes": "Bac + 5 + Concours",
    "competences": "Pédagogie, patience, autorité bienveillante",
    "tagsQuiz": ["enseignement", "transmission", "patience"],
    "formationsLiees": ["CRMEF", "Universités"],
    "parcours": "Bac → Licence → Master MEEF → Concours du CAPES → Formation au CRMEF",
    "bac": "Toutes (selon la matière)"
  },
  {
    "id": 20,
    "nom": "Éducateur spécialisé",
    "domaine": "ÉDUCATION, SOCIAL & SÉCURITÉ",
    "description": "Accompagne des personnes en difficulté pour les aider à s'insérer.",
    "salaire": "5 000 - 8 000 DH",
    "etudes": "Bac + 3",
    "competences": "Écoute, empathie, patience, créativité",
    "tagsQuiz": ["social", "aide", "écoute"],
    "formationsLiees": ["Écoles d'Éducateurs Spécialisés"],
    "parcours": "Bac → Concours d'entrée en école d'éducateur → 3 ans de formation",
    "bac": "Toutes"
  },
  {
    "id": 21,
    "nom": "Psychologue",
    "domaine": "ÉDUCATION, SOCIAL & SÉCURITÉ",
    "description": "Écoute et accompagne les personnes souffrant de difficultés psychologiques.",
    "salaire": "5 000 - 25 000 DH",
    "etudes": "Bac + 5",
    "competences": "Écoute active, neutralité bienveillante, discrétion",
    "tagsQuiz": ["écoute", "mental", "aide"],
    "formationsLiees": ["Facultés des Lettres et Sciences Humaines"],
    "parcours": "Bac → Licence en Psychologie → Master en Psychologie",
    "bac": "Toutes"
  },
  {
    "id": 22,
    "nom": "Officier de Police",
    "domaine": "ÉDUCATION, SOCIAL & SÉCURITÉ",
    "description": "Encadre les équipes, mène des enquêtes, assure la sécurité publique.",
    "salaire": "10 000 - 18 000 DH",
    "etudes": "Bac + 3 + Concours",
    "competences": "Leadership, sens du devoir, intégrité",
    "tagsQuiz": ["sécurité", "autorité", "justice"],
    "formationsLiees": ["École Royale de Police (ERP)"],
    "parcours": "Bac + 3 → Concours de l'ERP → Formation de 2 ans",
    "bac": "Toutes"
  },
  {
    "id": 23,
    "nom": "Officier de l'Armée",
    "domaine": "ÉDUCATION, SOCIAL & SÉCURITÉ",
    "description": "Cadre des Forces Armées Royales. Responsable d'unités, de missions, ou spécialiste technique.",
    "salaire": "10 000 - 25 000 DH",
    "etudes": "Bac + 2 à +5 selon concours",
    "competences": "Discipline, sens du sacrifice, leadership",
    "tagsQuiz": ["discipline", "nation", "leadership"],
    "formationsLiees": ["Académie Royale Militaire (ARM)", "Écoles de spécialités"],
    "parcours": "Bac S ou SM → Concours de l'ARM → Formation militaire et académique",
    "bac": "S ou Sciences Maths"
  },
  {
    "id": 24,
    "nom": "Ingénieur en Environnement",
    "domaine": "ENVIRONNEMENT, INDUSTRIE & TRANSPORTS",
    "description": "Trouve des solutions techniques aux problèmes de pollution, gestion des déchets, traitement de l'eau.",
    "salaire": "7 000 - 22 000 DH",
    "etudes": "Bac + 5",
    "competences": "Sens de l'écologie, esprit technique, réglementation",
    "tagsQuiz": ["écologie", "technique", "terrain"],
    "formationsLiees": ["Écoles d'Ingénieurs (EHTP, EMI, IAV)"],
    "parcours": "Bac S → École d'ingénieur avec option environnement ou Master spécialisé",
    "bac": "S"
  },
  {
    "id": 25,
    "nom": "Pilote de ligne",
    "domaine": "ENVIRONNEMENT, INDUSTRIE & TRANSPORTS",
    "description": "Commande un avion transportant des passagers ou du fret. Métier exigeant et très responsable.",
    "salaire": "30 000 - 150 000 DH",
    "etudes": "Bac + 2 à +3 (formation spécifique)",
    "competences": "Sang-froid, excellente santé, sens des responsabilités, anglais parfait",
    "tagsQuiz": ["aviation", "voyage", "responsabilité"],
    "formationsLiees": ["Écoles de pilotage agréées (privées)", "Royal Air Maroc (formation interne)"],
    "parcours": "Bac S (idéal) → Formation en école de pilotage (licence PPL, CPL) → Heures de vol → Formation sur avion de ligne",
    "bac": "S (idéal)"
  },
  {
    "id": 26,
    "nom": "Contrôleur aérien",
    "domaine": "ENVIRONNEMENT, INDUSTRIE & TRANSPORTS",
    "description": "Surveille et guide les avions dans le ciel et autour des aéroports pour assurer la sécurité.",
    "salaire": "15 000 - 40 000 DH",
    "etudes": "Bac + 2 à +3 (formation spécialisée)",
    "competences": "Concentration extrême, sang-froid, prise de décision rapide, anglais technique",
    "tagsQuiz": ["aviation", "sécurité", "concentration"],
    "formationsLiees": ["École Nationale de l'Aviation Civile (ENAC - France, avec bourses)", "Formations ONDA/privées"],
    "parcours": "Bac S → Concours de l'ENAC (très sélectif) ou formation reconnue par l'ONDA → Formation théorique et pratique intensive",
    "bac": "S"
  },
  {
    "id": 27,
    "nom": "Architecte d'intérieur",
    "domaine": "ARTS, COMMUNICATION & PATRIMOINE",
    "description": "Aménage et décore des espaces intérieurs (maisons, bureaux, boutiques) pour les rendre fonctionnels et esthétiques.",
    "salaire": "6 000 - 20 000 DH",
    "etudes": "Bac + 4 à +5",
    "competences": "Créativité, sens de l'espace, dessin, relation client",
    "tagsQuiz": ["créatif", "design", "espace"],
    "formationsLiees": ["Écoles d'architecture d'intérieur (privées, ESAV, etc.)", "École Nationale d'Architecture (ENA)"],
    "parcours": "Bac (toute filière) → École spécialisée en architecture d'intérieur (4-5 ans) ou Master après une licence en arts",
    "bac": "Toutes"
  },
  {
    "id": 28,
    "nom": "Journaliste",
    "domaine": "ARTS, COMMUNICATION & PATRIMOINE",
    "description": "Recherche, vérifie et présente des informations sur l'actualité via la presse, la TV, la radio ou le web.",
    "salaire": "5 000 - 20 000 DH",
    "etudes": "Bac + 3 à +5",
    "competences": "Curiosité, esprit critique, rédaction, aisance à l'oral",
    "tagsQuiz": ["écriture", "actualité", "enquête"],
    "formationsLiees": ["Écoles de journalisme (ISIC, IPJ, privées)", "Facultés des Lettres"],
    "parcours": "Bac → Licence en information-communication ou lettres → Master/École de journalisme",
    "bac": "Toutes"
  },
  {
    "id": 29,
    "nom": "Designer graphique",
    "domaine": "ARTS, COMMUNICATION & PATRIMOINE",
    "description": "Crée l'identité visuelle d'une entreprise (logo, site web, affiches, emballages) pour communiquer un message.",
    "salaire": "5 000 - 18 000 DH",
    "etudes": "Bac + 3 à +5",
    "competences": "Créativité, maîtrise des logiciels (Photoshop, Illustrator), sens de l'esthétique",
    "tagsQuiz": ["créatif", "visuel", "art"],
    "formationsLiees": ["Écoles des Beaux-Arts", "Écoles de design graphique (privées)", "ISTA spécialisé"],
    "parcours": "Bac (souvent option arts) → École de design/Beaux-Arts ou Licence en arts appliqués → Master/Spécialisation",
    "bac": "Option arts"
  },
  {
    "id": 30,
    "nom": "Traducteur-interprète",
    "domaine": "ARTS, COMMUNICATION & PATRIMOINE",
    "description": "Traduit des textes écrits (traducteur) ou restitue oralement des discours en temps réel (interprète) d'une langue à une autre.",
    "salaire": "6 000 - 25 000 DH",
    "etudes": "Bac + 5",
    "competences": "Maîtrise parfaite de 2+ langues, culture générale, rapidité, discrétion",
    "tagsQuiz": ["langues", "communication", "précision"],
    "formationsLiees": ["Écoles de Traduction (EST, Rabat)", "Facultés des Lettres (départements de langues)"],
    "parcours": "Bac (filière littéraire ou linguistique idéale) → Licence en Langues Étrangères Appliquées (LEA) ou Traduction → Master spécialisé",
    "bac": "Littéraire ou linguistique"
  },
  {
    "id": 31,
    "nom": "Urbaniste",
    "domaine": "ENVIRONNEMENT, INDUSTRIE & TRANSPORTS",
    "description": "Planifie l'aménagement des villes et des territoires pour qu'ils soient fonctionnels, durables et agréables à vivre.",
    "salaire": "8 000 - 25 000 DH",
    "etudes": "Bac + 5",
    "competences": "Vision globale, sens de l'organisation, connaissances juridiques et techniques",
    "tagsQuiz": ["ville", "organisation", "futur"],
    "formationsLiees": ["École Nationale d'Architecture (ENA)", "Institut National d'Aménagement et d'Urbanisme (INAU)"],
    "parcours": "Bac (Sciences Maths ou Éco) → École d'architecture (ENA) avec spécialisation urbanisme OU Master en urbanisme/aménagement",
    "bac": "Sciences Maths ou Éco"
  },
  {
    "id": 32,
    "nom": "Chef de projet digital",
    "domaine": "INGÉNIERIE & TECHNOLOGIE",
    "description": "Pilote la création d'un site web, d'une application ou d'une campagne digitale du début à la fin, en gérant budget, délais et équipe.",
    "salaire": "10 000 - 30 000 DH",
    "etudes": "Bac + 4 à +5",
    "competences": "Organisation, leadership, connaissances techniques de base, gestion client",
    "tagsQuiz": ["digital", "gestion", "équipe"],
    "formationsLiees": ["Écoles d'ingénieur (ENSIAS, etc.)", "Écoles de commerce", "Masters en management de projet"],
    "parcours": "Bac → École d'ingénieur/commerce ou Master en gestion/marketing digital → Expérience en gestion de projet",
    "bac": "Toutes"
  },
  {
    "id": 33,
    "nom": "Biologiste médical / Technicien de laboratoire",
    "domaine": "SANTÉ & MÉDECINE",
    "description": "Analyse des prélèvements (sang, urine, tissus) en laboratoire pour aider au diagnostic des maladies.",
    "salaire": "5 000 - 15 000 DH",
    "etudes": "Bac + 2 à +5",
    "competences": "Rigueur scientifique, précision, sens des responsabilités",
    "tagsQuiz": ["sciences", "analyse", "laboratoire"],
    "formationsLiees": ["Instituts de Formation aux Carrières de Santé (IFCS)", "Facultés des Sciences"],
    "parcours": "Bac S → BTS/DUT Analyses Biologiques ou Licence en Biologie → Formation spécifique ou Master pour les biologistes",
    "bac": "S"
  },
  {
    "id": 34,
    "nom": "Responsable logistique",
    "domaine": "ENVIRONNEMENT, INDUSTRIE & TRANSPORTS",
    "description": "Organise le transport et le stockage des marchandises, de l'usine au client, en optimisant coûts et délais.",
    "salaire": "8 000 - 25 000 DH",
    "etudes": "Bac + 4 à +5",
    "competences": "Organisation, esprit d'analyse, gestion des flux, négociation",
    "tagsQuiz": ["organisation", "transport", "gestion"],
    "formationsLiees": ["Écoles de commerce (spécialisation logistique)", "Écoles d'ingénieur", "Masters en logistique"],
    "parcours": "Bac → École de commerce/ingénieur ou Master en logistique/supply chain management",
    "bac": "Toutes"
  },
  {
    "id": 35,
    "nom": "Statisticien",
    "domaine": "INGÉNIERIE & TECHNOLOGIE",
    "description": "Collecte, traite et interprète des données chiffrées pour aider à la décision dans la santé, la finance, le marketing, etc.",
    "salaire": "8 000 - 25 000 DH",
    "etudes": "Bac + 5",
    "competences": "Esprit mathématique poussé, rigueur, maîtrise des logiciels statistiques",
    "tagsQuiz": ["maths", "données", "analyse"],
    "formationsLiees": ["Écoles d'ingénieur (ENSA, EMI)", "Facultés des Sciences (département Mathématiques)"],
    "parcours": "Bac Sciences Maths → Classes Préparatoires → École d'ingénieur en statistiques OU Licence/Master en Mathématiques Appliquées/Statistiques",
    "bac": "Sciences Maths"
  }
    // ... AJOUTEZ TOUS LES AUTRES MÉTIERS ICI ...
    // (Copiez les métiers 3 à 35 depuis votre fichier original)
];

console.log(`✅ ${window.jobsData.length} métiers chargés`);